### ISSUE TITLE
No Java installed during installion

### ISSUE THREAD

**Issue by Muto1899** [p3root/loxberry-habridge#1]
Hi Peter,

if I don't missunderstand anything, java is not installed during plugin installation but needed to run habridge. 

You could install it via the deamon file (this file has root permissions)

Regards,
Muto

**Comment by p3root** [comment]
look in the apt file, java should be installed indeed.

**Comment by p3root** [comment]
btw. my name is not peter :D call me patrik ;)

**Comment by Muto1899** [comment]
Oops atleast I got the P :)

The apt file has the followind content 

`# These packages will be installed by apt-get -y install PACKAGENAME
# One line per package, use exact packagename as you would do for apt-get.
#
oracle-java8-jdk`

This does not work. When I enter above comman manually I get 

> E: Unable to locate package oracle-java8-jdk

I think a source has to be added:

`

 echo "deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main" | tee /etc/apt/sources.list.d/webupd8team-java.list
echo "deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main" | tee -a /etc/apt/sources.list.d/webupd8team-java.list
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EEA14886`

However, I don't have much knowhow on Linux an copied this from the loxforum. There maybe another source needed. This one worked for me so far.

Regards,
Muto

**Comment by p3root** [comment]
I will check that today.

**Comment by p3root** [comment]
on my raspberry pi, i can find java:

`apt-cache search oracle-java8-jdk
oracle-java8-jdk - Java™ Platform, Standard Edition 8 Development Kit`

**Comment by Muto1899** [comment]
Maybe you installed it manually? I downloaded a fresh image of loxberry and installed the plugin. Please see the following part of the installation log:

> <OK> APT-Paketdatenbank wurde erfolgreich aktualisiert
><INFO> Installiere zusÃ¤tzliche Software-Pakete
><INFO> Command: /usr/bin/sudo /usr/bin/apt-get -q -y install oracle-java8-jdk
>Reading package lists...
>Building dependency tree...
>Reading state information...
>E: Unable to locate package oracle-java8-jdk
><ERROR> Paket konnte nicht installiert werden

**Comment by p3root** [comment]
try an` apt-get update`, maybe your package tree is not up-to-date.

**Comment by Muto1899** [comment]
This is already done before in standard plugin installation procedure. Here ist the full log:

**Comment by p3root** [comment]
ok, I will setup a new loxberry tonight and try to reproduce the issue.

**Comment by Muto1899** [comment]
any news? :)

**Comment by p3root** [comment]
sorry, I am waiting for a sd card. should arrive tomorrow.

**Comment by Muto1899** [comment]
ah ok, it is also available as a VM. That´s way less time consuming for test purposes

https://www.loxforum.com/forum/projektforen/loxberry/allgemeines-aa/55185-loxberry-vm-image

**Comment by p3root** [comment]
I think that the repository on the VM is a different as the one on the raspberry. But I'll give it a try.

**Comment by Muto1899** [comment]
Sorry for chasing, but any news here?

**Comment by p3root** [comment]
could you show me your sources.list? (cat /etc/apt/sources.list) 
thanks

**Comment by p3root** [comment]
or try apt-cache search java8 and copy paste me the output please.

**Comment by Muto1899** [comment]
Sorry for the late reply.

cat /etc/apt/sources.list

 `
deb http://ftp.de.debian.org/debian/ jessie main
deb-src http://ftp.de.debian.org/debian/ jessie main

deb http://security.debian.org/debian/ jessie/updates main
deb-src http://security.debian.org/debian/ jessie/updates main

deb http://ftp.de.debian.org/debian/ jessie/updates main
deb-src http://ftp.de.debian.org/debian/ jessie/updates main
`

For 'apt-cache search java8' I get no outpu back

**Comment by p3root** [comment]
Do you use the image from loxberry? Looks like different sources than I have, and I use the loxberry image.

**Comment by p3root** [comment]
Or do you use the vm image?

**Comment by Muto1899** [comment]
I use this one:
https://download.loxberry.de/stable/images/vmware/loxberry-image-vmware-0.2.2-frodo.zip

**Comment by p3root** [comment]
Ok, I thought that.
Therefore this is not a bug. The VMWare Image uses debian, debian has a different package source than raspbian. 

Follow this instruction, install JAVA8 once, and the package will work!
http://www.mkyong.com/java/how-to-install-oracle-jdk-8-on-debian/

**Comment by Muto1899** [comment]
Thanks, it's not a problem to install java on my machine. Did I get that correctly, that the installation will work on raspbian? I will test it tomorrow

**Comment by p3root** [comment]
Jep!

Outlook for Android<https://aka.ms/ghei36> herunterladen


________________________________
